In [1]:
import numpy as np

In [2]:
A = np.array([[1, 4, -1,3], [2, 1, -3,-1], [0, 2, 1,5]])

In [3]:
def row_echelon(M):
    """ Return Row Echelon Form of matrix A """
    A = np.copy(M)
    if (issubclass(A.dtype.type, np.integer)):
        A = A.astype(float)
    #A = M.astype(float)
    # if matrix A has no columns or rows,
    # it is already in REF, so we return itself
    r, c = A.shape
    if r == 0 or c == 0:
        return A

    # we search for non-zero element in the first column
    for i in range(len(A)):
        if A[i,0] != 0:
            break
    else:
        # if all elements in the first column is zero,
        # we perform REF on matrix from second column
        B = row_echelon(A[:,1:])
        # and then add the first zero-column back
        return np.hstack([A[:,:1], B])

    # if non-zero element happens not in the first row,
    # we switch rows
    if i > 0:
        ith_row = A[i].copy()
        A[i] = A[0]
        A[0] = ith_row

    # we divide first row by first element in it
    A[0] = A[0] / A[0,0]
    # we subtract all subsequent rows with first row (it has 1 now as first element)
    # multiplied by the corresponding element in the first column
    A[1:] -= A[0] * A[1:,0:1]

    # we perform REF on matrix from second row, from second column
    B = row_echelon(A[1:,1:])

    # we add first row and first (zero) column, and return
    return np.vstack([A[:1], np.hstack([A[1:,:1], B]) ])

In [4]:
row_echelon(A)

array([[ 1.        ,  4.        , -1.        ,  3.        ],
       [ 0.        ,  1.        ,  0.14285714,  1.        ],
       [ 0.        ,  0.        ,  1.        ,  4.2       ]])

In [5]:
import matplotlib.pyplot as plt 

In [6]:
res = np.array([0,0,0])

In [7]:
np.linalg.solve(A, res)

LinAlgError: Last 2 dimensions of the array must be square

In [12]:
B = np.array([[1-1j, 1j], [2, -1+1j]])

In [13]:
row_echelon(B)

array([[ 1. +0.j , -0.5+0.5j],
       [ 0. +0.j ,  0. +0.j ]])

In [29]:
C = np.array([[1, 1,2],[1,3,5], [1, 1, 4],[5,1,1]])

In [30]:
row_echelon(C)

array([[1. , 1. , 2. ],
       [0. , 1. , 1.5],
       [0. , 0. , 1. ],
       [0. , 0. , 0. ]])

In [31]:
D = np.array([1,3,5], [1, 1, 4]])
row_echelon(D)

array([[1. , 1. , 2. ],
       [0. , 1. , 1.5],
       [0. , 0. , 1. ]])

In [32]:
E = np.array([[1, 1,2],[1,3,5], [5,1,1]])
row_echelon(E)

array([[1. , 1. , 2. ],
       [0. , 1. , 1.5],
       [0. , 0. , 1. ]])

In [34]:
f = np.array([[1, 1,2], [1, 1, 4],[5,1,1]])
row_echelon(f)

array([[1.  , 1.  , 2.  ],
       [0.  , 1.  , 2.25],
       [0.  , 0.  , 1.  ]])

In [35]:
g = np.array([[1,1,1,1],[0,1j,1,1],[0,0,1j,0],[1,1,0,0]])
row_echelon(g)

array([[1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
       [0.+0.j, 1.+0.j, 0.-1.j, 0.-1.j],
       [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 1.-0.j]])

In [40]:
h = np.array([[1, 0,0,2], [0, -2, 3,-1],[-1,0,1,4],[0,1,-2,0]])
np.linalg.det(h)

-5.000000000000001