## Álgebra Lineal Computacional - 1C 2022

# Librería Numpy

### Contenidos
* <a href="#generalidades">Generalidades</a>
    * <a href="#size">Tamaño de una matriz</a>
    * <a href="#transpose">Transpuesta de una matriz</a>
    * <a href="#diag">Diagonal de una matriz</a>
    * <a href="#det">Determinante de una matriz</a>
    * <a href="#norm">Norma de una matriz o de un vector </a>
    * <a href="#copy">Copiar una matriz o un vector</a>
* <a href="#special">Matrices "especiales"</a>
    * <a href="#id">Matriz identidad</a>
    * <a href="#null">Matriz nula y vector nulo</a>
    * <a href="#ones">Matriz y vector de 1's</a>
    * <a href="#rand">Matriz y vector aleatorio</a>
    * <a href="#arange">Vector de rango de números (útil para cuando grafiquemos)</a>
* <a href="#ops">Operaciones</a>
    * <a href="#sum">Suma y resta</a>
    * <a href="#prod">Producto y división por un escalar</a>
    * <a href="#innerprod">Producto interno, producto matriz-matriz y matriz-vector</a>
* <a href="#solve">Sistemas de ecuaciones lineales</a>
    * <a href="#row_echelon">La función ``row_echelon`` para escalonar matrices</a>
* <a href="#coords">Accediendo a coordenadas de matrices y vectores</a>
    
***
Como siempre, empezamos importando Numpy:

In [1]:
import numpy as np

Para ver algunos ejemplos, definimos las siguientes matrices y vectores:

$$A = \begin{pmatrix} 3 & 2 & 2 \\ -1 & 0 & 1 \\ -2 & 2 & 4 \end{pmatrix} \quad 
B=\begin{pmatrix} 0 & 1 & -1 \\ 5 & -2 & 1 \end{pmatrix} \quad v = (-1, 2, 1)$$

In [2]:
A = np.array([[3, 2, 2], [-1, 0, 1], [-2, 2, 4]])
B = np.array([[0, 1, -1], [5, -2, 1]])
v = np.array([-1, 2, 1])

<a name="generalidades"></a>
## Generalidades

<a name="size"></a>
#### Tamaño de una matriz 
Lo obtenemos agregando ``.shape``. Devuelve una tupla donde el primer elemento corresponde a la cantidad de filas y el segundo a la cantidad de columnas:

In [3]:
B.shape

(2, 3)

In [4]:
# Si solamente quiero conocer la cantidad de filas:
B.shape[0]

# Si solamente quiero conocer la cantidad de columnas:
B.shape[1]

3

<a name="transpose"></a>
#### Transpuesta de una matriz
Lo hacemos agregando ``.T`` a la matriz:

In [5]:
A.T

array([[ 3, -1, -2],
       [ 2,  0,  2],
       [ 2,  1,  4]])

_**Obs**_: esto NO modifica a la matriz $A$, sino que crea un nuevo ``array`` que es la transpuesta de $A$.

Se puede _mezclar_ con otras operaciones. Por ejemplo, si queremos calcular $(BA)^T$

<a name="diag"></a>
#### Diagonal de una matriz
Si a ``np.diag`` le introducimos una matriz, nos devuelve su diagonal:

In [6]:
np.diag(A)

array([3, 0, 4])

Si le introducimos un vector, nos devuelve una matriz cuya diagonal es el vector y tiene $0$'s en los demás lugares:

In [7]:
np.diag(v)

array([[-1,  0,  0],
       [ 0,  2,  0],
       [ 0,  0,  1]])

<a name="det"></a>
#### Determinante de una matriz
Lo calculamos con la función ``np.linalg.det``:

In [8]:
np.linalg.det(A)

-6.0

<a name="inv"></a>
#### Inversa de una matriz
Si la matriz tiene inversa, la calculamos con ``np.linalg.inv``:

In [9]:
np.linalg.inv(A)

array([[ 0.33333333,  0.66666667, -0.33333333],
       [-0.33333333, -2.66666667,  0.83333333],
       [ 0.33333333,  1.66666667, -0.33333333]])

Si la matriz no es cuadrada o no tiene inversa, salta un error:

In [10]:
np.linalg.inv(B)  # Esta matriz no es cuadrada

LinAlgError: Last 2 dimensions of the array must be square

In [11]:
C = np.array([[0, 1, 1], [0, -1, 1j], [0, -2, 3]]) # Esta matriz no es inversible
print(C)
np.linalg.inv(C)

[[ 0.+0.j  1.+0.j  1.+0.j]
 [ 0.+0.j -1.+0.j  0.+1.j]
 [ 0.+0.j -2.+0.j  3.+0.j]]


LinAlgError: Singular matrix

<a name="norm"></a>
#### Norma de una matriz o de un vector 
Lo calculamos con la función ``np.linalg.norm``:

In [15]:
np.linalg.norm(v)

2.449489742783178

<a name="copy"></a>
#### Copiar una matriz o un vector
Si queremos crear una copia de una matriz o de un vector, lo hacemos añadiendo ``.copy()``:


In [16]:
C = A.copy()
C

array([[ 3,  2,  2],
       [-1,  0,  1],
       [-2,  2,  4]])

<a name="special"></a>
## Matrices "especiales"
<a name="id"></a>
#### Matriz identidad
Con la función ``np.eye(n)`` podemos definir la matriz identidad de tamaño $n\times n$. Por ejemplo, con ``np.eye(4)`` obtenemos la matriz identidad de $4\times4$:

In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

<a name="null"></a>
#### Matriz nula y vector nulo
La función ``np.zeros((m, n))`` nos permite obtener la matriz nula de tamaño $m\times n$. Por ejemplo, si queremos la matriz nula de tamaño $2\times 3$:

In [19]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

Si queremos el vector nulo de tamaño $3$:

In [20]:
np.zeros(3)

array([0., 0., 0.])

<a name="ones"></a>
#### Matriz y vector de 1's
Con ``np.ones`` obtenemos una matriz o vector del tamaño indicado con todos 1's. Su uso es análogo al de ``np.zeros``

In [21]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [22]:
np.ones(4)

array([1., 1., 1., 1.])

<a name="rand"></a>
#### Matriz y vector aleatorio
Podemos generar una matriz aleatoria con valores en $[0,1]$ de tamaño $m\times n$ con ``np.random.rand((m,n))``. Por ejemplo:

In [23]:
np.random.rand(3,4)

array([[0.17972456, 0.72265734, 0.24739592, 0.84930413],
       [0.33915087, 0.96492107, 0.31997808, 0.58987471],
       [0.69214645, 0.06824036, 0.71052581, 0.90586175]])

También sirve para generar vectores aleatorios:

In [24]:
np.random.rand(3)

array([0.71065195, 0.24521573, 0.50218901])

<a name="arange"></a>
#### Vector de rango de números (útil para cuando grafiquemos)
El comando ``arange`` permite generar un vector que contiene a todos los números en un determinado rango. La sintaxis es ``np.arange(inicio, fin, paso)`` donde ``fin`` no está incluido y ``paso`` es optativo (el valor por defecto es 1).

In [27]:
np.arange(1, 5)

array([1, 2, 3, 4])

In [28]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [29]:
np.arange(-1, 4, 0.1)

array([-1.00000000e+00, -9.00000000e-01, -8.00000000e-01, -7.00000000e-01,
       -6.00000000e-01, -5.00000000e-01, -4.00000000e-01, -3.00000000e-01,
       -2.00000000e-01, -1.00000000e-01, -2.22044605e-16,  1.00000000e-01,
        2.00000000e-01,  3.00000000e-01,  4.00000000e-01,  5.00000000e-01,
        6.00000000e-01,  7.00000000e-01,  8.00000000e-01,  9.00000000e-01,
        1.00000000e+00,  1.10000000e+00,  1.20000000e+00,  1.30000000e+00,
        1.40000000e+00,  1.50000000e+00,  1.60000000e+00,  1.70000000e+00,
        1.80000000e+00,  1.90000000e+00,  2.00000000e+00,  2.10000000e+00,
        2.20000000e+00,  2.30000000e+00,  2.40000000e+00,  2.50000000e+00,
        2.60000000e+00,  2.70000000e+00,  2.80000000e+00,  2.90000000e+00,
        3.00000000e+00,  3.10000000e+00,  3.20000000e+00,  3.30000000e+00,
        3.40000000e+00,  3.50000000e+00,  3.60000000e+00,  3.70000000e+00,
        3.80000000e+00,  3.90000000e+00])

<a name="ops"></a>
## Operaciones

<a name="sum"></a>
#### Sumas y restas
Si queremos sumar dos o más matrices o vectores, lo hacemos con ``+``. Si queremos restar, lo hacemos con ``-``. Naturalmente, las dimensiones de los sumandos deben ser iguales.

In [30]:
u = np.array([-3, 4, 5])
s = np.array([0, 2, 3])
u + v + s

array([-4,  8,  9])

Sumar un escalar a una matriz o a un vector equivale a sumarle el escalar a todas sus coordenadas:

In [31]:
print(A)
A + 2

[[ 3  2  2]
 [-1  0  1]
 [-2  2  4]]


array([[5, 4, 4],
       [1, 2, 3],
       [0, 4, 6]])

<a name="prod"></a>
#### Producto y división por un escalar
Si queremos multiplicar una matriz o un vector por un escalar, lo hacemos con ``*``. Si queremos dividir por un escalar, los hacemos con `/`:

In [32]:
print(B)
B*(-2)

[[ 0  1 -1]
 [ 5 -2  1]]


array([[  0,  -2,   2],
       [-10,   4,  -2]])

<a name="innerprod"></a>
#### Producto interno, producto matriz-matriz y matriz-vector

El producto interno entre vectores, el producto matriz-matriz y matriz-vector se realiza con ``@`` o con el comando ``np.dot``. 

**NO usar ``*`` para multiplicar matrices y/o vectores.**

In [33]:
# Para calcular A.v :
A @ v

# Es lo mismo que hacer:
np.dot(A,v)

array([ 3,  2, 10])

Hay que tener cuidado con las dimensiones!

In [34]:
# Como A es de 3x3 y B es de 2x3, no puedo calcular A.B :
A @ B

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [35]:
#Pero sí puedo calcular B.A :
B @ A

array([[ 1, -2, -3],
       [15, 12, 12]])

In [36]:
# También puedo calcular A por B transpuesta :
A @ B.T

array([[  0,  13],
       [ -1,  -4],
       [ -2, -10]])

<a name="solve"></a>
## Sistemas de ecuaciones lineales

Para resolver el sistema de ecuaciones lineales $Ax=b$ utilizamos ``np.linalg.solve(A,b)``. $A$ debe ser una matriz cuadrada.

In [37]:
np.linalg.solve(A, v)

array([ 0.66666667, -4.16666667,  2.66666667])

**Obs:** Esto es mejor que hacer ``np.linalg.inv(A) @ b``.

<a name="row_echelon"></a>
### La función ``row_echelon`` para escalonar matrices

En el campus está disponible el archivo ``row_echelon.py`` con la función que aplica Gauss para escalonar una matriz:

In [39]:
def row_echelon(M):
    """ Return Row Echelon Form of matrix A """
    A = np.copy(M)
    if (issubclass(A.dtype.type, np.integer)):
        A = A.astype(float)
    #A = M.astype(float)
    # if matrix A has no columns or rows,
    # it is already in REF, so we return itself
    r, c = A.shape
    if r == 0 or c == 0:
        return A

    # we search for non-zero element in the first column
    for i in range(len(A)):
        if A[i,0] != 0:
            break
    else:
        # if all elements in the first column is zero,
        # we perform REF on matrix from second column
        B = row_echelon(A[:,1:])
        # and then add the first zero-column back
        return np.hstack([A[:,:1], B])

    # if non-zero element happens not in the first row,
    # we switch rows
    if i > 0:
        ith_row = A[i].copy()
        A[i] = A[0]
        A[0] = ith_row

    # we divide first row by first element in it
    A[0] = A[0] / A[0,0]
    # we subtract all subsequent rows with first row (it has 1 now as first element)
    # multiplied by the corresponding element in the first column
    A[1:] -= A[0] * A[1:,0:1]

    # we perform REF on matrix from second row, from second column
    B = row_echelon(A[1:,1:])

    # we add first row and first (zero) column, and return
    return np.vstack([A[:1], np.hstack([A[1:,:1], B]) ])

Apliquémoslo a la matriz $A$:

In [40]:
row_echelon(A)

array([[1.        , 0.66666667, 0.66666667],
       [0.        , 1.        , 2.5       ],
       [0.        , 0.        , 1.        ]])

***
<a name="coords"></a>
## Accediendo a coordenadas de matrices y vectores

**IMPORTANTE: los índices en Python empiezan en 0**

Para obtener a la i-ésima coordenada de in vector, le agregamos ``[i]``:

In [41]:
print(v)
v[1]

[-1  2  1]


2

Si queremos obtener el lugar $i,j$ de la matriz $A$ (o sea, $a_{ij}$) lo hacemos agregando ``[i,j]``:

In [42]:
print(A)
A[1,2]

[[ 3  2  2]
 [-1  0  1]
 [-2  2  4]]


1

Si introducimos un valor que supera la cantidad de coordenadas de un vector o la cantidad de filas/columnas de una matriz, salta el siguiente error:

In [43]:
A[3,2]

IndexError: index 3 is out of bounds for axis 0 with size 3

Podemos obtener submatrices con la sintaxis ``inicio : fin`` donde se incluye el índice ``inicio`` y se excluye ``fin``. Por ejemplo, a continuación queremos obtener la submatriz de $A$ compuesta por los elementos de las primeras dos filas y  las primeras dos columnas:

In [44]:
print(A)
A[0:2, 0:2]

[[ 3  2  2]
 [-1  0  1]
 [-2  2  4]]


array([[ 3,  2],
       [-1,  0]])

Si ``inicio`` es $0$, podemos omitirlo. Así, podemos reescribir el ejemplo anterior de la siguiente manera:

In [45]:
print(A)
A[:2, :2]

[[ 3  2  2]
 [-1  0  1]
 [-2  2  4]]


array([[ 3,  2],
       [-1,  0]])

Análogamente, si queremos que ``final`` incluya a la última fila o columna, podemos omitir lo que viene después de ``:``. Por ejemplo, si quiero la submatriz de las últimas dos filas y primeras dos columnas de $A$:

In [46]:
print(A)
A[1:, :2]

[[ 3  2  2]
 [-1  0  1]
 [-2  2  4]]


array([[-1,  0],
       [-2,  2]])

Si sólo escribimos ``:`` Python lo interpreta que queremos todas las filas o todas las columnas:

In [47]:
# Quiero la fila 1 de A:
print('Fila 1 de A: ')
print(A[1, :])

# Quiero la columna 2 de A:
print('Columna 2 de A: ')
print(A[:, 2])

Fila 1 de A: 
[-1  0  1]
Columna 2 de A: 
[2 1 4]


Todo esto funciona también para vectores:

In [48]:
print(v)
v[1:]

[-1  2  1]


array([2, 1])

## Ejercicios

Sean:
$$
A = \begin{pmatrix} 0 & 2 & 2 \\ -1 & 0 & 1 \\ -1 & 1 & 4 \end{pmatrix} \quad 
B=\begin{pmatrix} 0 & 0 & -1 \\ 2 & 0 & 1 \end{pmatrix} \quad
C = \begin{pmatrix} 0 & 2 \\ -1 & 3 \\ 1 & -1 \end{pmatrix} \quad
v = (-1, 2, 0) \quad 
u = (3, 1, 2) \quad
w = (0, 3, -1)
$$

1) Definir en ``numpy`` las matrices y los vectores:

In [61]:
A = np.array([[0, 2, 2], [-1, 0, 1], [-1, 1, 4]])
B = np.array([[0, 0, -1], [2, 0, 1]])
C = np.array([[0, 2], [-1, 3], [1, -1]])
v = np.array([-1, 2, 0])
u = np.array([3, 1,2])
w = np.array([0, 3, -1])

2) Calcular:

a) $A^TC$

_Resultado_: $\begin{pmatrix} 0 & -2 \\ 1 & 3 \\ 3 & 3 \end{pmatrix}$

In [62]:
A.T @ C #Transpuesta de una matriz

array([[ 0, -2],
       [ 1,  3],
       [ 3,  3]])

b) $2BA + C^T$

_Resultado_: $\begin{pmatrix} 2 & -3 & -7 \\ 0 & 13 & 15 \end{pmatrix}$

In [63]:
2*B@A + C.T

array([[ 2, -3, -7],
       [ 0, 13, 15]])

c) $(Av)u$

_Resultado:_ $19$

In [64]:
(A@v)@u #no es el * ,es el prodcuto interno entre vectores

19

d) $A(vu)$

_Resultado:_ $\begin{pmatrix} 0 & -2 & -2 \\ 1 & 0 & -1 \\ 1 & -1 & -4 \end{pmatrix}$

In [73]:
A*(v@u) #entender las dimensiones y ver cuando es vector producto interno o una multiplicacion

array([[ 0, -2, -2],
       [ 1,  0, -1],
       [ 1, -1, -4]])

e) El producto interno entre la primera columna de $C$ y $w$

_Resultado_ : $-4$

In [67]:
C[:, 0]@ w #columna 0 es la primera columna

-4

f) $2v + (CB)w$

_Resultado_: $(-4, 0, 2)$

In [68]:
2*v +(C@B)@w

array([-4,  0,  2])

g) La solución del sistema $Ax=u$

_Resultado:_ $(-1.25,  1.75, -0.25)$

In [74]:
np.linalg.solve(A, u)#el x seria de incognita

array([-1.25,  1.75, -0.25])

h) $A^{-1}C$

_Resultado_: $\begin{pmatrix} 2 & -5.5 \\ -1 & 3.5 \\ 1 & -2.5 \end{pmatrix} $

In [75]:
np.linalg.inv(A) @ C

array([[ 2. , -5.5],
       [-1. ,  3.5],
       [ 1. , -2.5]])

i) El producto entre $C$ y la matriz que resulta de escalonar $B$

_Resultado_: $\begin{pmatrix} 0 & 0 & 2 \\ -1 & 0 & 2.5 \\ 1 & 0 & -0.5 \end{pmatrix}$

In [76]:
C@row_echelon(B)

array([[ 0. ,  0. ,  2. ],
       [-1. ,  0. ,  2.5],
       [ 1. ,  0. , -0.5]])

j) El producto entre $C$ y la transpuesta de la submatriz de $A$ compuesta por los elementos de las primeras dos filas y últimas dos columnas.

_Resultado_: $\begin{pmatrix} 4 & 2 \\ 4 & 3 \\ 0 & -1 \end{pmatrix}$

In [86]:
M=A[0:2,1:3] #fila/columna 0 , 1 agarra con 0:2 y con 1:3 agarra 1,2 
X=M.T
C @ X

array([[ 4,  2],
       [ 4,  3],
       [ 0, -1]])

k) $2||v - u||$

_Resultado:_ $9.16515138991168$


In [87]:
2*np.linalg.norm(v-u) #es adecuado para usar esta fórmula calcule la distancia


9.16515138991168